### PR TITLE
Fix graceful shutdown when intermediate or init process errors or panic

### LINKED ISSUE #237: Graceful shutdown Youki when forked process returns an error
Currently, if either the intermediate or the init process errors out, the Youki main process stucks on waiting for child ready message and cause the main process to hang. Some integration tests are deliberately testing for error conditions and requires Youki to shutdown gracefully. Also this is the right thing to do.

### PR DESCRIPTION
**Pull request by yihuaf**
Fix #237 Tracking #221 

Gracefully shutdown by closing down unused fds in the channel. In this case, when the child process exits, the parent waiting (read_exact) is exit blocking and error out. When fork, the fds in the channel are duplicated, so there are two receivers and two senders. Since we force the channel to become uni-directional, we can safely close the additional fds.

Also in the PR, we should only set host name when entering into a new UTS namespace. One of the integration test doesn't create any new uts namespace, so calling set_hostname is not a good idea.

Now pass one more integration test. The test essentially asks Youki to enter into the wrong type of namespace and see if Youki will error out.

### CODE REVIEW

File: src/process/channel.rs [hunk 1]
```diff
@@ -107,6 +109,18 @@ impl Channel {
...
+    pub fn close_receiver(&self) -> Result<()> {
+        unistd::close(self.receiver.as_raw_fd())?;
+
+        Ok(())
+    }
+
+    pub fn close_sender(&self) -> Result<()> {
+        unistd::close(self.sender.as_raw_fd())?;
+
+        Ok(())
```
Comment (utam0k) [inline src/process/channel.rs:121]: How about this code?
```suggestion
        unistd::close(self.receiver.as_raw_fd())
    }

    pub fn close_sender(&self) -> Result<()> {
        unistd::close(self.sender.as_raw_fd())
```

**Review by Furisto — APPROVED** [review]

File: src/process/channel.rs (hunk 1 above)
Comment (yihuaf) [reply src/process/channel.rs:121]: unistd functions will return a different error type than anyhow result, so we have to use `?` for a conversion.
