### PR TITLE
Fix how closure is transferred to the clone call.

### LINKED ISSUE #163: Using clone(2) to create the init container process segfault when build with release version of the youki binary
When building the released version of youki binary, the clone(2) used to create the container process will fail with the following error from dmesg:
```
[176643.245728] youki[340675]: segfault at 529 ip 00005581f9b434a0 sp 00007fff14905090 error 4 in youki[5581f9a20000+157000]
[176643.245741] Code: 00 00 ff d5 4c 89 bc 24 00 1c 00 00 48 89 9c 24 08 1c 00 00 4c 89 b4 24 10 1c 00 00 48 8b 84 24 18 03 00 00 48 8b 00 48 8b 00 <4c> 8b b8 28 05 00 00 48 8b 98 38 05 00 00 41 be 01 00 00 00 bd 01
```

Preliminary investigation points to the child stack pointer passed to clone(2) call. The debug version of the binary is not affected. Changing the allocated child stack size to 1MB or 2MB seems to make the issue go away, but I'd like a proper fix. Using this issue to track.

### PR DESCRIPTION
**Pull request by yihuaf**
The main objective of this PR is to fix how the closure is passed into the clone call. Because the new process created by `libc::clone` will execute the closure, and because of how rust manages the lifetime of memory, special care is needed to make sure the ownership of the memory associated with the closure is correctly transferred to the new process. Otherwise, the new process will only get a reference of the memory and LLVM can decide to free the memory right after the clone call returns in the parent process.

https://github.com/nix-rust/nix/issues/919 is an explanation of why `nix::sched::clone` wrapper has the exact same issue and is not implemented correctly. While there is a fix, https://github.com/nix-rust/nix/pull/920, but it seems to be abandoned since 2018. I took the hint from that PR as the basis of this PR.

Note: this patch is a bit complicated than I originally intended. So please double check if the comments around how the closure is passed to clone in fork.rs are easy to understand. This is a case where Rust makes this more painful but also illustrates that rust does force you to reason through how your code allocates memory correctly.

A follow up to fix #163

### CODE REVIEW

File: src/container/builder_impl.rs [hunk 1]
```diff
@@ -21,6 +21,24 @@ use crate::{
 
 use super::{Container, ContainerStatus};
 
+struct ContainerInitArgs {
```
Comment (utam0k) [inline src/container/builder_impl.rs:24]: Could you have the code placed a little closer to container_init() to make the relationship easier to understand? Or cutting it out into a file would be good too.

**Review by utam0k — CHANGES_REQUESTED** [review]
I commented on this, and I agree with you overall. I'll close the PR on my end.

File: src/container/builder_impl.rs (hunk 1 above)
Comment (yihuaf) [reply src/container/builder_impl.rs]: I moved it closer to container_init().

**Review by utam0k — APPROVED** [review]
awesome!
