### PR TITLE
Sync the state to confirm hooks execution

### LINKED ISSUE #3007: [Bug]: Rust OCI test is maybe flacky
### Bug Description

See https://github.com/youki-dev/youki/actions/runs/12028493866/job/33580623551?pr=2950
This is the first time I have seen rust oci tests failing at all. We need to validate what is the issue and fix it. The Go tests are already quiet flacky I would really prefer the rust test to not be flacky unless the fix is really hard or the frequency is really really small.

### Steps to Reproduce

Not sure, maybe run the failed test from CI https://github.com/youki-dev/youki/actions/runs/12028493866/job/33580623551?pr=2950 repeatedly.

### Expectation

_No response_

### System and Setup Info

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by donkomura**
## Description

The hooks test was flaky because it does not wait for delete operation unlike [the runtime-tools test](https://github.com/opencontainers/runtime-tools/blob/master/validation/hooks/hooks.go). This adds:
- `wait_for_state()` in utils to poll container state with timeout
  - this implementation comes from `lifecycle` tests, but it useful for other tests, so I implement it on utils
- Hook output file path changed to bundle directory to match runtime tool behavior

This ensures the test waits for the container to reach the expected state before proceeding, eliminating timing-related failures.

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Test updates
- [ ] CI/CD related changes
- [ ] Other (please describe):

## Testing

- [ ] Added new unit tests
- [ ] Added new integration tests
- [ ] Ran existing test suite
- [ ] Tested manually (please provide steps)

## Related Issues

Fixes #3007

### CODE REVIEW

File: tests/contest/contest/src/tests/hooks/invoke.rs [hunk 1]
```diff
@@ -1,38 +1,43 @@
...
+    bundle.as_ref().join("bundle").join("rootfs").join("output")
 }
 
-fn delete_hook_output_file() {
-    std::fs::remove_file(HOOK_OUTPUT_FILE).expect("fail to remove hook output file");
+fn delete_hook_output_file(path: &PathBuf) {
+    if path.exists() {
+        fs::remove_file(path).expect("failed to remove output file");
+    }
 }
```
Comment (nayuta723) [inline tests/contest/contest/src/tests/hooks/invoke.rs]: Instead of checking the path before deleting, please just delete the file and ignore the error if it’s a "NotFound" error.


```suggestion
fn delete_hook_output_file(path: &PathBuf) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => bail!("failed to remove output file: {}", e),
    }
}
```

File: tests/contest/contest/src/utils/test_utils.rs [hunk 2]
```diff
@@ -127,6 +127,76 @@ pub fn get_state<P: AsRef<Path>>(id: &str, dir: P) -> Result<(String, String)> {
...
+    poll_interval: Duration,
+) -> Result<()> {
+    let start = std::time::Instant::now();
+
+    while start.elapsed() < timeout {
+        match is_in_state(id, &dir, expected_state) {
+            Ok(true) => return Ok(()),
+            Ok(false) => std::thread::sleep(poll_interval),
+            Err(e) => {
+                if e.to_string().contains("does not exist") && expected_state == "stopped" {
```
Comment (nayuta723) [inline tests/contest/contest/src/utils/test_utils.rs]: Since `is_in_state` already handles the "does not exist" case, is this condition still necessary?

File: tests/contest/contest/src/utils/test_utils.rs [hunk 3]
```diff
@@ -127,6 +127,76 @@ pub fn get_state<P: AsRef<Path>>(id: &str, dir: P) -> Result<(String, String)> {
...
+                    Err(err) => bail!("Failed to parse state output as JSON: {} - {}", stdout, err),
+                }
+            }
+        }
+        Err(e) => Err(e.context("failed to get container state")),
+    }
+}
+
+/// Check if a container is in a specific state
+pub fn is_in_state<P: AsRef<Path>>(id: &str, dir: P, expected_state: &str) -> Result<bool> {
```
Comment (nayuta723) [inline tests/contest/contest/src/utils/test_utils.rs]: It's a bit unclear what this boolean value represents. Could you define an Enum or add a docstring to clarify it?

**Review by nayuta723 — COMMENTED** [review]
@donkomura 
Thanks, I’ve left a few minor comments.

File: tests/contest/contest/src/utils/test_utils.rs (hunk 2 above)
Comment (donkomura) [reply tests/contest/contest/src/utils/test_utils.rs]: As you've pointed out, this is indeed unnecessary. I'll remove it.

File: tests/contest/contest/src/utils/test_utils.rs (hunk 3 above)
Comment (donkomura) [reply tests/contest/contest/src/utils/test_utils.rs]: In the runtime-tools implementation, it was a string, but the correct state should be defined.

Well, I'll implement that as Enum.

Comment (nayuta723) [reply tests/contest/contest/src/utils/test_utils.rs]: I apologize for the confusion. My point was that the meaning of the true/false returned by `is_in_state` is unclear. As a proposed fix to make it clearer, how about adding a docstring explaining that the “does not exist” case is treated as `Stopped`?

File: tests/contest/contest/src/utils/test_utils.rs [hunk 4]
```diff
@@ -127,6 +136,78 @@ pub fn get_state<P: AsRef<Path>>(id: &str, dir: P) -> Result<(String, String)> {
...
+) -> Result<bool> {
+    match get_container_status(id, &dir) {
+        Ok(status) => Ok(status == expected_state),
+        Err(e) => {
+            if e.to_string().contains("does not exist") {
+                // regard non-existent container as stopped (delete after stopping)
+                if expected_state == LifecycleStatus::Stopped {
+                    return Ok(true);
+                }
+                return Ok(false);
```
Comment (nayuta723) [inline tests/contest/contest/src/utils/test_utils.rs]:
```suggestion
                // regard non-existent container as stopped (delete after stopping)
                return Ok(expected_state == LifecycleStatus::Stopped);
```

File: tests/contest/contest/src/utils/test_utils.rs [hunk 5]
```diff
@@ -127,6 +136,78 @@ pub fn get_state<P: AsRef<Path>>(id: &str, dir: P) -> Result<(String, String)> {
...
+    timeout: Duration,
+    poll_interval: Duration,
+) -> Result<()> {
+    let start = std::time::Instant::now();
+
+    while start.elapsed() < timeout {
+        match is_in_state(id, &dir, expected_state) {
+            Ok(true) => return Ok(()),
+            Ok(false) => std::thread::sleep(poll_interval),
+            Err(_) => std::thread::sleep(poll_interval),
```
Comment (nayuta723) [inline tests/contest/contest/src/utils/test_utils.rs]: Could you explain why we are ignoring errors and continuing to wait? If there is a specific reason for this behavior, please add a comment to clarify.

Comment (donkomura) [reply tests/contest/contest/src/utils/test_utils.rs]: [The runtime spec](https://specs.opencontainers.org/runtime-spec/runtime/) says, 'Additional values MAY be defined by the runtime.' So runtimes can optionally add their own states, which might cause JSON parse errors. However, it's spec-compliant, so no error should happen — we should just keep waiting for the expected state.

For other errors, we probably shouldn't ignore them (I'm not confident about this since I'm not reading the runtime spec).

File: tests/contest/contest/src/utils/test_utils.rs (hunk 3 above)
Comment (donkomura) [reply tests/contest/contest/src/utils/test_utils.rs]: I've got it. I'll make some explanations. Thank you for the suggestion!

File: tests/contest/contest/src/utils/test_utils.rs (hunk 5 above)
Comment (nayuta723) [reply tests/contest/contest/src/utils/test_utils.rs]: I agree. We should only ignore parse errors. For any other types of errors, we may return them immediately as errors, even before the timeout.

Comment (donkomura) [reply tests/contest/contest/src/utils/test_utils.rs]: I introduced error types to distinguish between parsing errors and other errors.

File: tests/contest/contest/src/utils/test_utils.rs [hunk 6]
```diff
@@ -127,6 +147,100 @@ pub fn get_state<P: AsRef<Path>>(id: &str, dir: P) -> Result<(String, String)> {
...
+/// Get the container status as a LifecycleStatus
+pub fn get_container_status<P: AsRef<Path>>(
+    id: &str,
+    dir: P,
+) -> Result<LifecycleStatus, ContainerStateError> {
+    let (stdout, stderr) = get_state(id, &dir).map_err(|e| {
+        if e.to_string().contains("does not exist") {
+            ContainerStateError::ContainerNotFound
+        } else {
+            ContainerStateError::Other(e.context("failed to get container state"))
```
Comment (nayuta723) [inline tests/contest/contest/src/utils/test_utils.rs]:
```suggestion
            ContainerStateError::Other(e)
```

**Review by nayuta723 — COMMENTED** [review]
I’ve left one comment.

File: tests/contest/contest/src/tests/hooks/invoke.rs [hunk 7]
```diff
@@ -77,27 +84,39 @@ fn get_test(test_name: &'static str) -> Test {
...
-                output
-                    .read_to_string(&mut log)
-                    .expect("fail to read hook log");
-                log
-            };
-            delete_hook_output_file();
+            wait_for_state(
+                &id_str,
+                bundle.path(),
+                LifecycleStatus::Stopped,
```
Comment (saku3) [inline tests/contest/contest/src/tests/hooks/invoke.rs]: Looking at this section in isolation, it may be confusing for future readers.
After delete, the container state no longer exists.

I think it would be better to introduce an enum like `WaitTarget` for `expected_state` in `is_in_state` and `wait_for_state`, so we can explicitly handle a `Deleted` (or `NotFound`) target.

Comment (donkomura) [reply tests/contest/contest/src/tests/hooks/invoke.rs]: Yeah, the current implementation is a bit too complex. I'm trying to clarify it along these lines like bellow. Does this seem reasonable?

```rust
pub enum WaitTarget {
    Status(LifecycleStatus),
    Deleted,
}
```

Comment (saku3) [reply tests/contest/contest/src/tests/hooks/invoke.rs]: Sorry for the late reply. This seems reasonable to me.

Comment (donkomura) [reply tests/contest/contest/src/tests/hooks/invoke.rs]: Thanks for the review. Fixed.
