### PR TITLE
Ensure youki runs under podman

### LINKED ISSUE #607: openSUSE Tumbleweed remove failure
I'm only getting the following error when I use podman with with `--rm` argument

```bash
$ cat /etc/os-release 
NAME="openSUSE Tumbleweed"
VERSION_ID="20220102"
...
$ uname -a
Linux localhost 5.15.12-1-default #1 SMP Wed Dec 29 14:50:16 UTC 2021 (375fcb8) x86_64 x86_64 x86_64 GNU/Linux
$ podman --version
podman version 3.4.4
$ cat  /etc/containers/containers.conf 
[containers]
[network]
[engine]
runtime = "crun"
[engine.runtimes]
runc = [
        "/usr/bin/runc",
]
crun = [
        "/usr/bin/crun",
]
youki = [
        "/usr/bin/youki",
]
$ sudo podman --runtime youki run --rm quay.io/quay/busybox:latest ls
bin
dev
etc
foo
home
proc
root
run
sys
tmp
usr
var
Error: failed to delete container 1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f

Caused by:
    0: failed to remove cgroup machine.slice:libpod:1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f
    1: could not remove control group machine.slice:libpod:1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f
    2: failed to stop unit libpod-1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f.scope
    3: Unit libpod-1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f.scope not loaded.
ERRO[0000] Error removing container 1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f: error cleaning up container 1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f: error removing container 1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f from runtime: `/usr/bin/youki delete --force 1f23b94934b1234b5227adc4ce2c7c9459ed314e92d08bb4e974057afc72f42f` failed: exit status 1 
```

Another way to reproduce it:

```bash
$ sudo podman --runtime youki run -d quay.io/quay/busybox:latest sleep infinity
52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60
sudo youki list
ID                                                                PID   STATUS   BUNDLE                                                                                                                    CREATED                    CREATOR
52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60  5931  Running  /var/lib/containers/storage/overlay-containers/52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60/userdata  2022-01-11T02:39:09+01:00  root
$ sudo /usr/bin/youki delete --force 52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60
Error: failed to delete container 52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60

Caused by:
    0: failed to remove cgroup machine.slice:libpod:52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60
    1: could not remove control group machine.slice:libpod:52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60
    2: failed to stop unit libpod-52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60.scope
    3: Unit libpod-52a1161b72bec9f19b0edbd9627df54c01394ff1d05be07930d6a28852056f60.scope not loaded.****
```

### PR DESCRIPTION
**Pull request by Furisto**
We need to be more defensive when deleting a container as podman executes delete twice and cleans up the cgroup of the container before we have a chance to clean it up.

Fixes #607

### CODE REVIEW

**Comment by utam0k** [comment]
Wow, I was surprised to know that.
> podman executes delete twice

File: crates/youki/src/commands/delete.rs [hunk 1]
```diff
@@ -1,11 +1,15 @@
-use crate::commands::load_container;
+use crate::commands::{container_exists, load_container};
 use anyhow::{Context, Result};
 use std::path::PathBuf;
 
 use liboci_cli::Delete;
 
 pub fn delete(args: Delete, root_path: PathBuf) -> Result<()> {
```
Comment (utam0k) [inline crates/youki/src/commands/delete.rs:7]: In the `delete()`, the `construct_container_root` is called three times. Can we make `construct_container_root()` execute only a time?

Comment (Furisto) [reply crates/youki/src/commands/delete.rs:7]: Thought about it, but I am only counting one additional allocation which won't made a big difference and it made the code less readable.

**Review by utam0k — APPROVED** [review]

**Comment by utam0k** [comment]
LGTM
