### PR TITLE
fix(3293) Ambient capabilities are not applied as expected

### LINKED ISSUE #3293: [Bug]: Ambient capabilities are not applied as expected
### Bug Description

Ambient capabilities are not applied as expected

The root cause lies in the implementation of `drop_privileges` for ambient capabilities.

https://github.com/youki-dev/youki/blob/main/crates/libcontainer/src/capabilities.rs#L155

```
    if let Some(ambient) = cs.ambient() {
        // check specifically for ambient, as those might not always be available
        if let Err(e) = syscall.set_capability(CapSet::Ambient, &to_set(ambient)) {
            tracing::warn!("failed to set ambient capabilities: {}", e);
        }
    }
```

### In youki
Inside `syscall.set_capability` (as shown in the code above), it iterates over a `HashSet`—which does not guarantee a fixed order—to apply capabilities one by one.
If an error occurs partway through, execution returns from this code.
Because of that, the `for` loop does not always run to completion when an error happens, and some capabilities may end up not being applied.

### In runc
Errors are handled inside the loop, so the `for` loop always runs to completion.

https://github.com/opencontainers/runc/blob/59a5ff14a2c1f6beb74982a9c03e31c5fb49859d/libcontainer/capabilities/capabilities.go#L142C1-L147C3

```
	for _, a := range ambs {
		err := capability.SetAmbient(true, a)
		if err != nil {
			logrus.Warnf("can't raise ambient capability %s: %v", capToStr(a), err)
		}
	}
```

### Steps to Reproduce

1. prepare config.json

We specify capabilities in the ambient set that are not included in the permitted and inheritable sets.

```
    "args": [
      "sh", "-c", "grep '^CapAmb' /proc/self/status"
    ],

...
    "capabilities": {
      "bounding": [
        "CAP_NET_BIND_SERVICE",
        "CAP_AUDIT_WRITE",
        "CAP_KILL"
      ],
      "effective": [
        "CAP_NET_BIND_SERVICE",
        "CAP_AUDIT_WRITE",
        "CAP_KILL"
      ],
      "inheritable": [
        "CAP_NET_BIND_SERVICE",
        "CAP_AUDIT_WRITE",
        "CAP_KILL"
      ],
      "permitted": [
        "CAP_NET_BIND_SERVICE",
        "CAP_AUDIT_WRITE",
        "CAP_KILL"
      ],
      "ambient": [
        "CAP_NET_BIND_SERVICE",
        "CAP_AUDIT_WRITE",
        "CAP_KILL",
        "CAP_SYSLOG"    ←←←←←←←←←←← operation not permitted 
      ]
    },
```

2. run youki multiple times

```
$ youki run -b tutorial/ container
CapAmb: 0000000020000420
$ youki run -b tutorial/ container
CapAmb: 0000000020000420
$ youki run -b tutorial/ container
CapAmb: 0000000000000000
$ youki run -b tutorial/ container
CapAmb: 0000000020000020
$ youki run -b tutorial/ container
CapAmb: 0000000020000420
```

If you run the following command, it becomes even clearer:

```
strace -f -e trace=prctl youki run -b tutorial/ container
```

### Expectation

In the above case

since
CAP_NET_BIND_SERVICE: 0x0000000000000400
CAP_AUDIT_WRITE: 0x0000000020000000
CAP_KILL: 0x0000000000000020

```
$ youki run -b tutorial/ container
CapAmb: 0000000020000420
```

### System and Setup Info

_No response_

### Additional Context

related: https://github.com/youki-dev/youki/pull/3210

### PR DESCRIPTION
**Pull request by tommady**
## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Test updates
- [ ] CI/CD related changes
- [ ] Other (please describe):

## Testing

- [ ] Added new unit tests
- [ ] Added new integration tests
- [x] Ran existing test suite
- [x] Tested manually (please provide steps)

## Related Issues

Fixes #3293

## Additional Context

follow the **Steps to Reproduce** and **Expectation** from the issue

### CODE REVIEW

**Comment by tommady** [comment]
hi @saku3 
please help review while you have time.
thanks.

File: crates/libcontainer/src/syscall/linux.rs [hunk 1]
```diff
@@ -507,6 +507,13 @@ impl Syscall for LinuxSyscall {
                     caps::drop(None, CapSet::Bounding, *c)?
                 }
             }
+            CapSet::Ambient => {
+                value.iter().for_each(|c| {
+                    if let Err(e) = caps::raise(None, CapSet::Ambient, *c) {
+                        tracing::warn!(?e, "can't raise ambient capability");
```
[the remark this answers is not in the document]
Comment (saku3) [reply crates/libcontainer/src/syscall/linux.rs]: @tommady 
Please make sure that cap `c` is also logged.

File: crates/libcontainer/src/syscall/linux.rs [hunk 2]
```diff
@@ -507,6 +507,13 @@ impl Syscall for LinuxSyscall {
                     caps::drop(None, CapSet::Bounding, *c)?
                 }
             }
+            CapSet::Ambient => {
+                value.iter().for_each(|c| {
```
Comment (saku3) [inline crates/libcontainer/src/syscall/linux.rs]: Please keep the original comment as is.
It would also be nice to add a comment mentioning that if it fails, we emit a warn log and continue with the subsequent processing.

File: crates/libcontainer/src/syscall/linux.rs [hunk 3]
```diff
@@ -507,6 +507,20 @@ impl Syscall for LinuxSyscall {
...
             }
+            CapSet::Ambient => {
+                // check specifically for ambient, as those might not always be available
+                //
+                // Ambient capabilities are applied from an unordered HashSet, and if any
+                // set_capability() call fails, Youki stops applying the rest. This causes
+                // inconsistent CapAmb results between runs and diverges from runc, which
+                // continues applying all ambient caps even after a failure. The same flawed
+                // ambient-cap logic also causes exec-path capability test failures.
+                for c in value {
```
Comment (saku3) [inline crates/libcontainer/src/syscall/linux.rs:519]: @tommady 
Sorry, one more comment.

I think it would be better to clear them in the same way as runc does.

https://github.com/opencontainers/runc/blob/59a5ff14a2c1f6beb74982a9c03e31c5fb49859d/libcontainer/capabilities/capabilities.go#L134

I believe you can just call `caps::clear` before the `for` loop:

```rust
caps::clear(None, CapSet::Ambient)?;
```

Comment (tommady) [reply crates/libcontainer/src/syscall/linux.rs:519]: sure, not a problem

**Review by saku3 — APPROVED** [review]
Thanks!

It looks good for me.

```sh
for i in {1..100}; do youki run -b tutorial/ a; done
```

I ran the above command locally and confirmed that the result is consistent.
(However, I’m not sure how we should write a test for this...)

**Comment by saku3** [comment]
@utam0k @YJDoc2 
PTAL

**Comment by tommady** [comment]
> May I ask you to add the e2e test(`contest`)?

Hi @utam0k,
there will be an e2e test in this PR
https://github.com/youki-dev/youki/pull/3210
which is the reason why @saku3 found this issue

is that ok with you?

**Comment by saku3** [comment]
As tommady commented, once this PR(#3210) is merged, there shouldn’t be any regressions related to this issue.
