### PR TITLE
Handle relative paths

### LINKED ISSUE #720: Failed to create container when using relative root path
When using youki with relative root path creating container fails. From looking at a code it is probably due to not converting path to absolute path and using `chdir`.

Steps to reproduce:
```
mkdir -p ./some/dir
./youki --root ./some/dir create -b [BUNDLE] some-id
```
Error: `Error: No such file or directory`

I can look into it and try to fix it.

### PR DESCRIPTION
**Pull request by Szymongib**
This PR improves the handling of relative paths for `root_path` and `pid_file`. I decided to create the specified directory early in `determine_root_path` if it does not exist, as this seems to be the only way to `canonicalize` path prior to creating container dir (path needs to exist otherwise `canonicalize` will fail). This results in the directory being created for other commands like `list` or `delete` also which might not be ideal, but `runc` seems to work this way either so decided to stick with it.

Also not sure about canonicalizing those paths in `ContainerBuilder` as it disrupts the interface slightly by introducing `Result<Self>` as a return type to some methods, however, I did not find a better place for that so if anyone has some suggestions please let me know.

Additionally, I have added context to a few errors that made it easier to initially troubleshoot.

Fixes #720

<a href="https://gitpod.io/#https://github.com/containers/youki/pull/740"></a>

### CODE REVIEW

File: crates/libcontainer/src/container/builder.rs [hunk 1]
```diff
@@ -101,11 +103,14 @@ impl<'a> ContainerBuilder<'a> {
...
+    /// .with_root_path("/run/containers/youki").expect("invalid root path");
     /// ```
-    pub fn with_root_path<P: Into<PathBuf>>(mut self, path: P) -> Self {
-        self.root_path = path.into();
-        self
+    pub fn with_root_path<P: Into<PathBuf>>(mut self, path: P) -> Result<Self> {
+        self.root_path = path
+            .into()
+            .canonicalize()
+            .context("failed to canonicalize root path")?;
```
Comment (Furisto) [inline crates/libcontainer/src/container/builder.rs:112]:
```suggestion
            .with_context(||format!("failed to canonicalize root path {:?}", path))?;
```

File: crates/libcontainer/src/container/builder.rs [hunk 2]
```diff
@@ -117,11 +122,19 @@ impl<'a> ContainerBuilder<'a> {
...
     /// ```
-    pub fn with_pid_file<P: Into<PathBuf>>(mut self, path: Option<P>) -> Self {
-        self.pid_file = path.map(|p| p.into());
-        self
+    pub fn with_pid_file<P: Into<PathBuf>>(mut self, path: Option<P>) -> Result<Self> {
+        self.pid_file = if let Some(p) = path {
+            Some(
+                p.into()
+                    .canonicalize()
+                    .context("failed canonicalize pid file path")?,
```
Comment (Furisto) [inline crates/libcontainer/src/container/builder.rs:132]:
```suggestion
                    .with_context(|| format!("failed canonicalize pid file path"))?,
```

File: crates/libcontainer/src/container/init_builder.rs [hunk 3]
```diff
@@ -39,10 +39,14 @@ impl<'a> InitContainerBuilder<'a> {
...
-
-        let mut container = self.create_container_state(&container_dir)?;
+        let spec = self.load_spec().context("failed to load spec")?;
+        let container_dir = self
+            .create_container_dir()
+            .context("failed to create container dir")?;
+
+        let mut container = self
+            .create_container_state(&container_dir)
+            .context("failed to create container state")?;
```
Comment (Furisto) [inline crates/libcontainer/src/container/init_builder.rs:49]: 👍

File: crates/libcontainer/src/container/builder.rs (hunk 1 above)
Comment (Szymongib) [reply crates/libcontainer/src/container/builder.rs]: Needed to adjust it slightly as `Into<PathBuf>` is not `Debug`.

File: crates/libcontainer/src/container/builder.rs (hunk 2 above)
Comment (Szymongib) [reply crates/libcontainer/src/container/builder.rs]: Did you mean to add the `path` here too? Adjusted it similarly to the other one.

**Review by Furisto — APPROVED** [review]

**Comment by Furisto** [comment]
@Szymongib 💯
