### PR TITLE
Fix recursive mount_setattr handling for rec_attr and improve mounts_recursive tests

### LINKED ISSUE #3320: rbind,ro mount is read-only but not recursively
Part of [runc compatibilities](https://github.com/youki-dev/youki/issues/3178) or bug

## Description

When specifying `rbind,ro` as mount options, the mount itself should be read-only, but it is not expected to be applied recursively as read-only.

However, in youki, it becomes read-only recursively.

see also

https://github.com/opencontainers/runc/blob/main/tests/integration/mounts_recursive.bats#L34C18-L34C65

## Steps to Reproduce

We create the mounts as a prerequisite setup.

```
TMP_DIR=$(mktemp -d)
TESTVOLUME="${TMP_DIR}/mounts_recursive"
mkdir -p ${TESTVOLUME}
sudo mount -t tmpfs none "${TESTVOLUME}"
echo "foo" > "${TESTVOLUME}/foo"
sudo mkdir -p "${TESTVOLUME}/subvol"
sudo mount -t tmpfs none "${TESTVOLUME}/subvol"
echo "bar" > "${TESTVOLUME}/subvol/bar"
```

setup config.json

configure mounts that use the pre-created `mount` as the source.

```
    {
      "destination": "/mnt",
      "source": "/tmp/tmp.E1PRXLfMTc/mounts_recursive",
      "options": [
        "rbind",
        "ro"
      ]
    }
```

run youki

```
youki run -b tutorial/ container
```

### In a different terminal.

This behaves as expected.

```
$ youki exec a touch /mnt/foo
touch: /mnt/foo: Read-only file system
```

This is not expected to be read-only.
```
$ youki exec a touch /mnt/subvol/bar
touch: /mnt/subvol/bar: Read-only file system
```

## Additional Context

There were some mount-related fixes in v0.5.7, but this behavior existed even before that.

### PR DESCRIPTION
**Pull request by saku3**
## Description

* Fix recursive mount_setattr handling for rec_attr 
  * The scope of `mount_setattr` was not clearly defined, which could cause options that should apply only to the top-level mount to be mixed with options that should be applied recursively to submounts. Therefore, I separated the logic so that rec_attr is applied recursively.
  * Add rbind+ro mount test. ref: [runc test](https://github.com/opencontainers/runc/blob/main/tests/integration/mounts_recursive.bats#L34)
* Improve mounts_recursive tests
  * parts of the` mounts_recursive tests` were not actually verifying `submounts`, making it difficult to catch regressions in recursive mount attributes. Therefore, I updated the tests to verify the submounts.
  * I also made a few additional improvements, listed below:
    * rro_test, rrw_test
      * The tests did not actually verify read-only behavior for files, so I added a file write check.
    * rsuid_test
      * Previously, the test only checked whether the SUID bit was set. I changed it to execute the binary and verify the effective behavior (similar to `rnosuid`).
    * rsymfollow_test, rnosymfollow_test
      * Previously, the tests only checked whether the target was a symlink. However, even with `nosymfollow`, the file remains a symlink, so the test was not meaningful. I updated the tests to actually check whether the symlink can be followed.

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Performance improvement
- [x] Test updates
- [ ] CI/CD related changes
- [ ] Other (please describe):

## Testing

- [ ] Added new unit tests
- [x] Added new integration tests
- [ ] Ran existing test suite
- [ ] Tested manually (please provide steps)

## Related Issues

Fixes #3320

### CODE REVIEW

File: crates/libcontainer/src/rootfs/mount.rs [hunk 1]
```diff
@@ -683,11 +675,22 @@ impl Mount {
...
                 mount_fd,
                 Path::new(""),
-                at_flags,
+                linux::AT_EMPTY_PATH,
                 &mount_attr,
                 mem::size_of::<linux::MountAttr>(),
             )?;
 
+            // rec_attr is applied recursively
+            if let Some(mount_attr) = &mount_option_config.rec_attr {
```
Comment (utam0k) [inline crates/libcontainer/src/rootfs/mount.rs]: Using the same variable name can lead to confusion. How about using a different name?

Comment (saku3) [reply crates/libcontainer/src/rootfs/mount.rs]: I fixed it.

File: tests/contest/runtimetest/src/tests.rs [hunk 2]
```diff
@@ -321,6 +320,32 @@ pub fn validate_mounts_recursive(spec: &Spec) {
...
+    match test_write_access(path.to_str().unwrap()) {
+        Err(_) => {}
+        Ok(()) => {
+            eprintln!(
+                "in readonly paths, path expected to not be writable, found writable: {}",
+                path.display()
+            );
+            return;
+        }
+    }
```
Comment (utam0k) [inline tests/contest/runtimetest/src/tests.rs]: You can use if-let or match! here.

File: tests/contest/contest/src/tests/mounts_recursive/mod.rs [hunk 3]
```diff
@@ -587,27 +757,57 @@ fn check_recursive_rsymfollow() -> TestResult {
...
 }
 
-/// this mount test how to work?
-/// 1. Create mount_options based on the mount properties of the test
-/// 2. Create OCI.Spec content, container one process is runtimetest,(runtimetest is cargo model, file path `tests/runtimetest/`)
-/// 3. inside container to check if the actual mount matches the spec, (spec https://man7.org/linux/man-pages/man2/mount_setattr.2.html),
-///    eg. tests/runtimetest/src/tests.rs
+// this mount test how to work?
+// 1. Create mount_options based on the mount properties of the test
+// 2. Create OCI.Spec content, container one process is runtimetest,(runtimetest is cargo model, file path `tests/runtimetest/`)
```
Comment (utam0k) [inline tests/contest/contest/src/tests/mounts_recursive/mod.rs]:
```suggestion
// 2. Create OCI Spec content, container one process is runtimetest,(runtimetest is cargo model, file path `tests/runtimetest/`)
```

File: tests/contest/contest/src/tests/mounts_recursive/mod.rs [hunk 4]
```diff
@@ -89,15 +89,37 @@ fn setup_mount(mount_dir: &Path, sub_mount_dir: &Path) {
         .unwrap();
 }
 
+fn setup_remount(mount_dir: &Path, sub_mount_dir: &Path, flag: MsFlags) {
+    mount::<Path, Path, str, str>(None, mount_dir, None, MsFlags::MS_REMOUNT | flag, None).unwrap();
+    mount::<Path, Path, str, str>(None, sub_mount_dir, None, MsFlags::MS_REMOUNT | flag, None)
+        .unwrap();
```
Comment (utam0k) [inline tests/contest/contest/src/tests/mounts_recursive/mod.rs]:
```suggestion
    mount::<Path, Path, str, str>(None, mount_dir, None, MsFlags::MS_REMOUNT | flag, None)?;
    mount::<Path, Path, str, str>(None, sub_mount_dir, None, MsFlags::MS_REMOUNT | flag, None)?;
```

Comment (saku3) [reply tests/contest/contest/src/tests/mounts_recursive/mod.rs]: fixed. I’ve fixed `clean_mount` and `setup_mount` as well.

File: tests/contest/contest/src/tests/mounts_recursive/mod.rs (hunk 3 above)
Comment (saku3) [reply tests/contest/contest/src/tests/mounts_recursive/mod.rs]: fixed.

File: tests/contest/runtimetest/src/tests.rs (hunk 2 above)
Comment (saku3) [reply tests/contest/runtimetest/src/tests.rs]: I’ve fixed it. Thanks!

**Comment by saku3** [comment]
It’s timing out, but based on my local verification, the tests were passing.

**Comment by utam0k** [comment]
> It’s timing out, but based on my local verification, the tests were passing.

hmm... Might need to tune the context performance a bit.

**Review by utam0k — APPROVED** [review]
