### PR TITLE
Include container status to IncorrectStatus error messaging

### LINKED ISSUE #3410: IncorrectStatus error should include container status
### Issue:

In `IncorrectStatus`' [current implementation](https://github.com/youki-dev/youki/blob/main/crates/libcontainer/src/error.rs), the error message `failed to perform operation due to incorrect container status` is generic and does not offer the container’s status to help the user resolve the issue.

The status is logged via `tracing::error!` but isn't carried by the error itself, so it's lost in the propagated `Caused by` chain.

### Proposed Solution:

I propose adding `ContainerStatus` to `LibcontainerError::IncorrectStatus` and include the status in the error message.

```rust
#[derive(Debug, thiserror::Error)]
pub enum LibcontainerError{
    #[error("failed to perform operation due to the container's status: `{0}`")]
    IncorrectStatus(ContainerStatus),
}
```

Resulting in:

```bash
Before:
failed to perform operation due to incorrect container status

After:
failed to perform operation due to the container's status: `Running`
```

### Alternative:
Open to discussion regarding alternatives, like different wording, including the name of the operation being performed, and container’s id in the error message.

**Happy to submit a PR if this approach works.**

### PR DESCRIPTION
**Pull request by CarloQuick**
## Description
`IncorrectStatus` was using generic error message, so I included `ContainerStatus` to the `IncorrectStatus` error variant.

```bash
// Before
Caused by:
failed to perform operation due to incorrect container status

// After
Caused by:
failed to perform operation due to the container's status: `Running`
```

## Type of Change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Test updates
- [ ] CI/CD related changes
- [ ] Other (please describe):

## Testing

- [x] Added new unit tests
- [ ] Added new integration tests
- [x] Ran existing test suite
- [x] Tested manually (please provide steps)

- **Added unit test**: `test_libcontainer_error_msg` to verify correct formatting and display of each container status in the error messaging.
- **Ran existing test suite**: Ran `libcontainer` tests locally with `cargo test -p libcontainer`, 
`tty::tests::test_setup_console` and `tty::tests::test_verify_ptmx_handle_with_real_pty` fail locally. (These appear to be pre-existing environment-specific failures (devpts on WSL2), unrelated to this change.)
- **Tested manually**: I created a container, and while running attempted to delete it without the force flag. The displayed error message contained the container's status. 

## Related Issues

Fixes #3410 

## Additional Context

n/a

### CODE REVIEW

File: crates/libcontainer/src/error.rs [hunk 1]
```diff
@@ -12,8 +14,8 @@ pub enum MissingSpecError {
 
 #[derive(Debug, thiserror::Error)]
 pub enum LibcontainerError {
-    #[error("failed to perform operation due to incorrect container status")]
-    IncorrectStatus,
+    #[error("failed to perform operation due to the container's status: `{0}`")]
```
Comment (YJDoc2) [inline crates/libcontainer/src/error.rs]: nit:
```suggestion
    #[error("failed to perform operation due to unexpected container status: `{0}`")]
```

My reasoning is that the error message should have some indication that this status was not correct/expected. Previously, we used to say `incorrect status`.

However, not a blocker, but like to hear opinion.

Comment (CarloQuick) [reply crates/libcontainer/src/error.rs]: This makes sense. 

The operation being requested is wrong for the status.

What are your thoughts the following? 
```bash
failed operation due to incompatible container status: `Running`
```

Comment (utam0k) [reply crates/libcontainer/src/error.rs]: LGTM

Comment (CarloQuick) [reply crates/libcontainer/src/error.rs]: @utam0k are you referring to [suggested wording](https://github.com/youki-dev/youki/pull/3411#discussion_r2820134011), correct?

Comment (utam0k) [reply crates/libcontainer/src/error.rs]: Right.

Comment (CarloQuick) [reply crates/libcontainer/src/error.rs]: @utam0k @YJDoc2 
Thank you both for your feedback. I've fixed the message wording here: [ce81de3](https://github.com/youki-dev/youki/pull/3411/commits/ce81de3beaf8eb625e2424975feb93bc1ada2a05)

**Comment by utam0k** [comment]
@CarloQuick Thanks for your contribution!
