### PR TITLE
Fixed container init process not re-parent to youki main process

### LINKED ISSUE #1601: Use `clone(2)` instead of `fork(2)`
# Why?

We have to need to use `CLONE_PARENT` but unfortunately `fork(2)` doesn't support it.
Without CLONE_PARENT, the init process becomes a zombie process and no one can `wait(2)`.
For example, it is a problem when trying to implement the exec and wait commands.

### PR DESCRIPTION
**Pull request by yihuaf**
Fix #1601 

In this PR, I decided to clone `intermediate` process as child and then clone the container init process as sibling of the `intermediate` process and child of `youki main` process. In this way, when intermediate process exits, the container init process will not re-parent to pid 1 and become zombie. The caller of youki can decide to use subreaper flag to adopt the container init process when youki main process exits.

This method cleaner because youki main process is guaranteed to be the parent of both intermediate process and container init process at all time. There is no extra re-parenting.

This PR is only part of the fix. We do need to revisit the detached and foreground mode. Not everything is fixed, but this PR should maintain the old behavior on anything that it does not fix.

### CODE REVIEW

**Comment by yihuaf** [comment]
See this comment for more discussion: https://github.com/containers/youki/issues/1601#issuecomment-1459499447

File: crates/libcontainer/src/container/init_builder.rs [hunk 1]
```diff
@@ -90,10 +90,15 @@ impl<'a> InitContainerBuilder<'a> {
             notify_path,
             container: Some(container.clone()),
             preserve_fds: self.base.preserve_fds,
-            detached: false, // TODO this should be set properly based on how the command is given
+            // TODO: This should be set properly based on how the command is
+            // given. For now, set the detached to true because this is what
+            // `youki create` defaults to.
+            detached: true,
```
Comment (utam0k) [inline crates/libcontainer/src/container/init_builder.rs:96]: Please create the issue about this comment.

File: crates/libcontainer/src/process/container_main_process.rs [hunk 2]
```diff
@@ -110,13 +96,22 @@ pub fn container_main_process(container_args: &ContainerArgs) -> Result<(Pid, Pi
...
-    // intermediate pid is required in the case when we call exec, as we need to wait for the
-    // intermediate process to exit, which itself waits for child process (the exec process) to exit
-    // in order to get the proper exit code. We cannot simply wait for the init_pid , that is the actual container
-    // process, as it is not (direct) child of our process
-    Ok((intermediate_pid, init_pid))
+    // Before the main process returns, we want to make sure the intermediate
+    // process is exit and reaped. By this point, the intermediate process
+    // should already exited successfully. If intermediate process errors out,
+    // the `init_ready` will not be sent.
+    match waitpid(intermediate_pid, None)? {
```
Comment (utam0k) [inline crates/libcontainer/src/process/container_main_process.rs:103]: Does this affect the exec command?

File: crates/libcontainer/src/container/init_builder.rs (hunk 1 above)
Comment (yihuaf) [reply crates/libcontainer/src/container/init_builder.rs:96]: I will do this. I was planning to fix this right after since this will be required to enable foreground mode. I want this PR to make all the detached mode situation work and `youki create` defaults to detached but `youki run` has a flag to switch between foreground and background mode.

Comment (yihuaf) [reply crates/libcontainer/src/container/init_builder.rs:96]: Actually https://github.com/containers/youki/issues/317 and https://github.com/containers/youki/issues/628 covers the situation fairly well.

File: crates/libcontainer/src/process/container_main_process.rs (hunk 2 above)
Comment (yihuaf) [reply crates/libcontainer/src/process/container_main_process.rs:103]: No. This is reaping the intermediate process, so `create`, `run`, `exec` all have to reap this process correctly, which is expected to always exit and the `youki main` process should wait for the intermediate process to exit and reap it.

Comment (utam0k) [reply crates/libcontainer/src/process/container_main_process.rs:103]: :ok:

**Review by utam0k — APPROVED** [review]
:100:
